### ISSUE TITLE
3.65 Devkit support

### ISSUE THREAD

**Issue by Exeedy** [OperationNT414C/ShellSecBat#6]
Please add support for 3.65 devkit /dex.

Thank you for your awesome work!

**Comment by OperationNT414C** [comment]
Hello,
I got the offsets for 3.65 PTEL and PDEL units from nowrep repository. Here is the compiled file:
[ShellSecBat_3.65_PTEL_PDEL.zip](https://github.com/OperationNT414C/ShellSecBat/files/2216074/ShellSecBat_3.65_PTEL_PDEL.zip)
Before I officially create a new release, can you confirm me if it works? (because I don't own such units)
Thank you for your help.

**Comment by Exeedy** [comment]
Thank you i'll test it now.

[EDIT]

Yes it works!
No issues everything works.

Thank you very much
