### ISSUE TITLE
Date overlapping with Application Icons

### ISSUE THREAD

**Issue by DewGaming** [OperationNT414C/ShellSecBat#8]
When I use the data feature, it will overlap with the icons that appear in the Info Bar, even if there are no applications open, just the home screen.  Config and screenshots below.

---

### Configs
Features:11
Time:111/
Drives:11.111111
LeftKey:101
RightKey:201

### Screenshots

![2020-01-09-132235](https://user-images.githubusercontent.com/24654288/72098023-46804d80-32e3-11ea-9c32-48e24f6dcf10.png)

![2020-01-09-131744](https://user-images.githubusercontent.com/24654288/72097819-cfe35000-32e2-11ea-9ae7-b818f9e09a67.png)

**Comment by OperationNT414C** [comment]
I am aware of this limitation, it was already mentioned here:
https://github.com/OperationNT414C/ShellSecBat/issues/1

> "because it quicky "goes beyond" opened application icons"

 but there is nothing that can be done (there is no text anchor point available in SceShell at right side of the screen), except reducing the amount of informations display.
For example, you can disable the year display (because I don't think it's a relevant information) by replacing "Time:111/" with "Time:110/" but you will still have overlap when there are 3 applications opened.
Sorry for the inconvenience.
